# Comment to a new issue.
issuesOpened: >
  Thank you for issuesOpened an issue. We will try and get back to you as soon as possible.

  Please make sure you have given us as much context as possible.

pullRequestOpened: >
  Thank you for pullRequestOpened your pull request.

  Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
  
  
pullRequestOpened: >
  Thank you for pullRequestOpened your pull request.
  
pullRequestClosed: >
  Thank you for pullRequestClosed your pull request.
  
pullRequestReviewRequested: >
  Thank you for pullRequestReviewRequested your pull request.
  
pullRequestReviewRequestRemoved: >
  Thank you for pullRequestReviewRequestRemoved your pull request.
  
pullRequestLabeled: >
  Thank you for pullRequestLabeled your pull request.
  
pullRequestUnlabeled: >
  Thank you for pullRequestUnlabeled your pull request.
  
pullRequestEdited: >
  Thank you for pullRequestEdited your pull request.
  
pullRequestClosed: >
  Thank you for pullRequestClosed your pull request.
  
pullRequestReopened: >
  Thank you for pullRequestReopened your pull request.
  
pullRequestAssigned: >
  Thank you for pullRequestAssigned your pull request.
  
pullRequestUnassigned: >
  Thank you for pullRequestUnassigned your pull request.
  
